on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Tests

jobs:
  latest:
    name: Stable Rust
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Lint with clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets

  minimum:
    name: Minimum Rust (1.31)
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.31.0
          override: true
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
